#' Create input-output make and use coefficients from PECAS AA accounts
#'
#' @param pecas_makeuse A tibble containing statewide input-output flows in
#'   annual dollars, generated by the PECAS AA module
#' @param sector_categories A tibble containing the equivalencies between PECAS
#'   `Activity`s and the firm categories used in the CT module
#' @param sctg_codes A vector that includes all of the two-digit SCTG codes
#'   included in the currently used Freight Analysis Framework (FAF). The
#'   default values are those that have appeared in FAF version 4 and 5, and
#'   will most likely remain that way until the next revision of SCTG codes
#'
#' @details This function converts the PECAS input-output flows by sector into
#'   make and use coefficients, used to map commodities produced or consumed by
#'   each sector (make and use coefficients, respectively). PECAS already
#'   splits flows between transportable and non-transportable commodities,
#'   making our job simpler. We simply have to put the data, which is produced
#'   for each year PECAS runs, into format we need. The transportable goods are
#'   defined using Standard Classification of Transportable Goods (SCTG) codes,
#'   which are also used in USDOT data, including their Freight Analysis
#'   Framework (FAF), which we uses to define inter-regional flows. We read the
#'   FAF data in this function to create a list of each commodity defined within
#'   it, which is compared to those found in the make-use data. An error is
#'   thrown if one or more commodities are found in the FAF that are not in the
#'   make-use data (although not vice-versa, for there might be local production
#'   not included in the inter-regional flows). The user can optionally save the
#'   derived coefficients in a text file in comma-separated value format.
#'
#' @export
#' @examples
#' make_use <- create_makeuse_coefficients(pecas_makeuse, sector_equiv, faf_data)

create_makeuse_coefficients <- function(pecas_makeuse, sector_categories,
  sctg_codes = c(1:41, 43)) {
  # Announce yourself
  print(swimctr:::self_identify(match.call()), quote = FALSE)

  # Use the two-digit SCTG2 codes defined in the CFS by default unless the
  # user has specified a different set. The codes are handled as strings
  # instead of integers in the make and use coefficients file (they're
  # embedded in the `Commodity` variable), so we will ensure that they're
  # in that format in this function.
  all_commodities <- stringr::str_pad(as.character(sctg_codes), 2, pad = '0')
  all_commodities <- sort(unique(all_commodities))  # In case of duplicates

  # Start by processing the make coefficients
  make <- filter(pecas_makeuse, MorU == "M") %>%
    # Remove non-transportable commodities, and extract two-digit SCTG from those
    # that remain
    mutate(prefix = tolower(substr(Commodity, 1, 4)),
      sctg2 = ifelse(prefix == "sctg", substr(Commodity, 5, 6), NA)) %>%
    filter(!is.na(sctg2)) %>%

    # Remove households and imports from the activities, as we are only
    # concerned with who locally produces each commodity
    filter(!str_detect(Activity, "_impt"), !str_detect(Activity, "HH")) %>%

    # Associate CT firm categories with the PECAS `sector` types
    left_join(., sector_categories, by = "Activity") %>%

    # Finally, calculate the resulting factors based upon the remaining fields
    group_by(MorU, category, sctg2) %>%
    summarise(Amount = sum(Amount)) %>%
    mutate(coefficient = Amount / sum(Amount))

  # Tell us the dimensions of the resulting make coefficients table
  print(paste("Deriving", nrow(make), "make coefficients for",
    length(unique(make$category)), "firm categories by",
    length(unique(make$sctg2)), "commodities"), quote = FALSE)

  # Figure out how many commodities do not have corresponding make coefficients
  make_commodities <- sort(unique(make$sctg2))
  not_found <- paste0(setdiff(all_commodities, make_commodities), collapse = ' ')
  if (not_found != '') {
    print(paste("Make coefficients not found for SCTG code(s)", not_found),
      quote = FALSE)
  }

  # We will do more or less the same thing for the use coefficients
  use <- pecas_makeuse %>%
    filter(MorU == "U") %>%

    # As before, remove non-transportable commodities, and extract the two-digit
    # SCTG code from commodity field for those that remain
    mutate(prefix = tolower(substr(Commodity, 1, 4)),
      sctg2 = ifelse(prefix == "sctg", substr(Commodity, 5, 6), NA)) %>%
    filter(!is.na(sctg2)) %>%

    # Remove exports from the activities, for we are only trying to portray
    # competing internal activities
    filter(!str_detect(Activity, "_expt")) %>%

    # We will collapse all households into a single activity category of the
    # same name, for they are valid consumers of transportable commodities
    mutate(prefix = substr(Activity, 1, 2),
      Activity = ifelse(prefix == "HH", "households", Activity)) %>%

    # Associate CT firm categories with the PECAS `Activity` types
    left_join(., sector_categories, by = "Activity") %>%

    # And now we're finally ready to calculate the use coefficients
    group_by(MorU, category, sctg2) %>%
    summarise(Amount = sum(Amount)) %>%
    mutate(coefficient = Amount/sum(Amount))

  # Tell us the outcome
  print(paste("Deriving", nrow(use), "use coefficients for",
    length(unique(use$sctg2)), "commodities by",
    length(unique(use$category)), "firm categories"), quote = FALSE)

  # Figure out how many commodities do not have corresponding make coefficients
  use_commodities <- sort(unique(use$sctg2))
  not_found <- paste0(setdiff(all_commodities, use_commodities), collapse = ' ')
  if (not_found != '') {
    print(paste("Use coefficients not found for SCTG code(s)", not_found),
      quote = FALSE)
  }

  # Recombine the two tables into a single file
  makeuse <- bind_rows(make, use) %>%
    select(-Amount) %>%
    arrange(MorU, category, sctg2)

  # Return the combined table
  makeuse
}
